# permissions for end users to view preemptionlimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preemptionlimit-viewer-role
  labels:
    rbac.kueue.x-k8s.io/role: "preemptionlimit-viewer"
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - preemptionlimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - preemptionlimits/status
  verbs:
  - get
