/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// NumericLabelConstraintApplyConfiguration represents a declarative configuration of the NumericLabelConstraint type for use
// with apply.
//
// NumericLabelConstraint describes the configurations for filtering a numerical label.
// For example, this can be used to filter candidates based on topology domains, such as the
// "number of TPUs". If a preemptor requires a large topology, you can set key="tpu-size"
// and relation="Lower", allowing it to preempt smaller workloads rather than disrupting
// other large topology workloads.
// Please note that you should remember to append the designated label to the list of labels
// copied to the workload via the Kueue main configuration.
type NumericLabelConstraintApplyConfiguration struct {
	// Key is the label key that stores the integer value.
	Key *string `json:"key,omitempty"`
	// DefaultValue is used when a workload does not have the label key
	// or value under the key cannot be parsed as an integer.
	// If not specified workloads without the label or
	// with label value not parsable as int are treated as incomparable by relation (if specified),
	// and therefore excluded from preemption candidates.
	DefaultValue *int32 `json:"defaultValue,omitempty"`
	// Relation defines how the preemptor compares to the candidate.
	Relation *kueuev1beta2.RelativeConstraint `json:"relation,omitempty"`
	// MinValue specifies the lowest label value a workload must have to be considered for preemption.
	// If not specified, no lower bound is enforced.
	MinValue *int32 `json:"minValue,omitempty"`
	// MaxValue specifies the highest label value a workload must have to be considered for preemption.
	// If not specified, no upper bound is enforced.
	MaxValue *int32 `json:"maxValue,omitempty"`
}

// NumericLabelConstraintApplyConfiguration constructs a declarative configuration of the NumericLabelConstraint type for use with
// apply.
func NumericLabelConstraint() *NumericLabelConstraintApplyConfiguration {
	return &NumericLabelConstraintApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *NumericLabelConstraintApplyConfiguration) WithKey(value string) *NumericLabelConstraintApplyConfiguration {
	b.Key = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *NumericLabelConstraintApplyConfiguration) WithDefaultValue(value int32) *NumericLabelConstraintApplyConfiguration {
	b.DefaultValue = &value
	return b
}

// WithRelation sets the Relation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Relation field is set to the value of the last call.
func (b *NumericLabelConstraintApplyConfiguration) WithRelation(value kueuev1beta2.RelativeConstraint) *NumericLabelConstraintApplyConfiguration {
	b.Relation = &value
	return b
}

// WithMinValue sets the MinValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinValue field is set to the value of the last call.
func (b *NumericLabelConstraintApplyConfiguration) WithMinValue(value int32) *NumericLabelConstraintApplyConfiguration {
	b.MinValue = &value
	return b
}

// WithMaxValue sets the MaxValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxValue field is set to the value of the last call.
func (b *NumericLabelConstraintApplyConfiguration) WithMaxValue(value int32) *NumericLabelConstraintApplyConfiguration {
	b.MaxValue = &value
	return b
}
