/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// OrderApplyConfiguration represents a declarative configuration of the Order type for use
// with apply.
//
// Order specifies a single sorting criterion and direction for ordering preemption candidates.
// Multiple Order criteria are evaluated sequentially as a multi-key comparator chain,
// with ties broken by Workload UID for deterministic ordering.
type OrderApplyConfiguration struct {
	// OrderingField specifies the field to sort preemption candidates by.
	OrderingField *kueuev1beta2.OrderingField `json:"orderingField,omitempty"`
	// Direction specifies the sorting direction (Ascending or Descending).
	// Defaults to Ascending if not specified.
	Direction *kueuev1beta2.OrderingDirection `json:"direction,omitempty"`
}

// OrderApplyConfiguration constructs a declarative configuration of the Order type for use with
// apply.
func Order() *OrderApplyConfiguration {
	return &OrderApplyConfiguration{}
}

// WithOrderingField sets the OrderingField field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrderingField field is set to the value of the last call.
func (b *OrderApplyConfiguration) WithOrderingField(value kueuev1beta2.OrderingField) *OrderApplyConfiguration {
	b.OrderingField = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *OrderApplyConfiguration) WithDirection(value kueuev1beta2.OrderingDirection) *OrderApplyConfiguration {
	b.Direction = &value
	return b
}
