/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PreemptionRuleApplyConfiguration represents a declarative configuration of the PreemptionRule type for use
// with apply.
type PreemptionRuleApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	// Label Selector indicating which workloads can trigger preemptions
	// using this rule.
	MatchingPreemptorWorkloads *v1.LabelSelectorApplyConfiguration `json:"matchingPreemptorWorkloads,omitempty"`
	// ActivationPolicy determines when this rule is used.
	ActivationPolicy *PreemptionRuleActivationPolicyApplyConfiguration `json:"activationPolicy,omitempty"`
	// Selection rules for workloads that are candidates for preemption.
	// Candidates resulting from multiple selectors are summed into one set. No selectors result in empty candidate set, thereby disallowing any preemptions with this rule.
	Candidates []PreemptionCandidateSelectorApplyConfiguration `json:"candidates,omitempty"`
}

// PreemptionRuleApplyConfiguration constructs a declarative configuration of the PreemptionRule type for use with
// apply.
func PreemptionRule() *PreemptionRuleApplyConfiguration {
	return &PreemptionRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PreemptionRuleApplyConfiguration) WithName(value string) *PreemptionRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithMatchingPreemptorWorkloads sets the MatchingPreemptorWorkloads field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchingPreemptorWorkloads field is set to the value of the last call.
func (b *PreemptionRuleApplyConfiguration) WithMatchingPreemptorWorkloads(value *v1.LabelSelectorApplyConfiguration) *PreemptionRuleApplyConfiguration {
	b.MatchingPreemptorWorkloads = value
	return b
}

// WithActivationPolicy sets the ActivationPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivationPolicy field is set to the value of the last call.
func (b *PreemptionRuleApplyConfiguration) WithActivationPolicy(value *PreemptionRuleActivationPolicyApplyConfiguration) *PreemptionRuleApplyConfiguration {
	b.ActivationPolicy = value
	return b
}

// WithCandidates adds the given value to the Candidates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Candidates field.
func (b *PreemptionRuleApplyConfiguration) WithCandidates(values ...*PreemptionCandidateSelectorApplyConfiguration) *PreemptionRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCandidates")
		}
		b.Candidates = append(b.Candidates, *values[i])
	}
	return b
}
