/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// PreemptionCandidateSelectorApplyConfiguration represents a declarative configuration of the PreemptionCandidateSelector type for use
// with apply.
type PreemptionCandidateSelectorApplyConfiguration struct {
	// Required.
	RelationRequirement *kueuev1beta2.PreemptionRelationConstraint `json:"relationRequirement,omitempty"`
	// Accepts all if not set
	// Filter candidate workloads using custom numeric labels from the workload
	// resource.
	// Multiple numeric labels are joined using AND-rule (all have to be satisfied).
	NumericLabels []NumericLabelConstraintApplyConfiguration `json:"numericLabels,omitempty"`
	// The comparison is made against the preempting workload.
	// Lower means that the candidate
	// has lower priority than the preemptor and so on. No check is made
	// if the field is nil.
	RelativeWorkloadPriority *kueuev1beta2.RelativeConstraint `json:"relativeWorkloadPriority,omitempty"`
}

// PreemptionCandidateSelectorApplyConfiguration constructs a declarative configuration of the PreemptionCandidateSelector type for use with
// apply.
func PreemptionCandidateSelector() *PreemptionCandidateSelectorApplyConfiguration {
	return &PreemptionCandidateSelectorApplyConfiguration{}
}

// WithRelationRequirement sets the RelationRequirement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RelationRequirement field is set to the value of the last call.
func (b *PreemptionCandidateSelectorApplyConfiguration) WithRelationRequirement(value kueuev1beta2.PreemptionRelationConstraint) *PreemptionCandidateSelectorApplyConfiguration {
	b.RelationRequirement = &value
	return b
}

// WithNumericLabels adds the given value to the NumericLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NumericLabels field.
func (b *PreemptionCandidateSelectorApplyConfiguration) WithNumericLabels(values ...*NumericLabelConstraintApplyConfiguration) *PreemptionCandidateSelectorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNumericLabels")
		}
		b.NumericLabels = append(b.NumericLabels, *values[i])
	}
	return b
}

// WithRelativeWorkloadPriority sets the RelativeWorkloadPriority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RelativeWorkloadPriority field is set to the value of the last call.
func (b *PreemptionCandidateSelectorApplyConfiguration) WithRelativeWorkloadPriority(value kueuev1beta2.RelativeConstraint) *PreemptionCandidateSelectorApplyConfiguration {
	b.RelativeWorkloadPriority = &value
	return b
}
