/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// PreemptionRuleActivationPolicyApplyConfiguration represents a declarative configuration of the PreemptionRuleActivationPolicy type for use
// with apply.
//
// PreemptionRuleActivationPolicy determines when a preemption rule is used.
type PreemptionRuleActivationPolicyApplyConfiguration struct {
	// Trigger is the condition that activates the rule.
	Trigger *kueuev1beta2.PreemptionRuleTrigger `json:"trigger,omitempty"`
}

// PreemptionRuleActivationPolicyApplyConfiguration constructs a declarative configuration of the PreemptionRuleActivationPolicy type for use with
// apply.
func PreemptionRuleActivationPolicy() *PreemptionRuleActivationPolicyApplyConfiguration {
	return &PreemptionRuleActivationPolicyApplyConfiguration{}
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *PreemptionRuleActivationPolicyApplyConfiguration) WithTrigger(value kueuev1beta2.PreemptionRuleTrigger) *PreemptionRuleActivationPolicyApplyConfiguration {
	b.Trigger = &value
	return b
}
