/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
	applyconfigurationkueuev1beta2 "sigs.k8s.io/kueue/client-go/applyconfiguration/kueue/v1beta2"
	scheme "sigs.k8s.io/kueue/client-go/clientset/versioned/scheme"
)

// PreemptionConfigsGetter has a method to return a PreemptionConfigInterface.
// A group's client should implement this interface.
type PreemptionConfigsGetter interface {
	PreemptionConfigs() PreemptionConfigInterface
}

// PreemptionConfigInterface has methods to work with PreemptionConfig resources.
type PreemptionConfigInterface interface {
	Create(ctx context.Context, preemptionConfig *kueuev1beta2.PreemptionConfig, opts v1.CreateOptions) (*kueuev1beta2.PreemptionConfig, error)
	Update(ctx context.Context, preemptionConfig *kueuev1beta2.PreemptionConfig, opts v1.UpdateOptions) (*kueuev1beta2.PreemptionConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kueuev1beta2.PreemptionConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*kueuev1beta2.PreemptionConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kueuev1beta2.PreemptionConfig, err error)
	Apply(ctx context.Context, preemptionConfig *applyconfigurationkueuev1beta2.PreemptionConfigApplyConfiguration, opts v1.ApplyOptions) (result *kueuev1beta2.PreemptionConfig, err error)
	PreemptionConfigExpansion
}

// preemptionConfigs implements PreemptionConfigInterface
type preemptionConfigs struct {
	*gentype.ClientWithListAndApply[*kueuev1beta2.PreemptionConfig, *kueuev1beta2.PreemptionConfigList, *applyconfigurationkueuev1beta2.PreemptionConfigApplyConfiguration]
}

// newPreemptionConfigs returns a PreemptionConfigs
func newPreemptionConfigs(c *KueueV1beta2Client) *preemptionConfigs {
	return &preemptionConfigs{
		gentype.NewClientWithListAndApply[*kueuev1beta2.PreemptionConfig, *kueuev1beta2.PreemptionConfigList, *applyconfigurationkueuev1beta2.PreemptionConfigApplyConfiguration](
			"preemptionconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kueuev1beta2.PreemptionConfig { return &kueuev1beta2.PreemptionConfig{} },
			func() *kueuev1beta2.PreemptionConfigList { return &kueuev1beta2.PreemptionConfigList{} },
		),
	}
}
